name: Clean up preview cron

on:
  schedule:
    - cron: 0 0 * * *

jobs:
  run-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Cleanup job
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ env.PREVIEW_URL }}/api/cleanup
          method: 'GET'